# # name: Deploy Azure Dev Environment

# on:
#   push:
#     paths:
#       - "environments/dev/**"
#       - "modules/**"
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository code
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Install Terraform using hashicorp setup
#       - name: Install Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.6.6

#       # Azure CLI login using service principal credentials stored in GitHub secrets
#       - name: Azure CLI Login
#         run: |
#           az login --service-principal \
#             --username ${{ secrets.AZURE_CLIENT_ID }} \
#             --password ${{ secrets.AZURE_CLIENT_SECRET }} \
#             --tenant ${{ secrets.AZURE_TENANT_ID }}
#           az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       # Terraform initialization (downloads necessary providers and modules)
#       - name: Terraform Init
#         working-directory: environments/dev
#         run: terraform init

#       # Terraform Plan step to create the execution plan
#       - name: Terraform Plan
#         working-directory: environments/dev
#         run: terraform plan -out=tfplan.out

#       # Terraform Apply only on 'main' branch (to avoid accidental deployments on other branches)
#       - name: Terraform Apply
#         if: github.ref == 'refs/heads/main'
#         working-directory: environments/dev
#         run: terraform apply -auto-approve tfplan.out
