name: Deploy Azure Prod Environment

on:
  push:
    paths:
      - "environments/prod/**"
      - "modules/**"
      - ".github/workflows/main.yml"
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan (Prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Azure CLI Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: environments/prod
        run: terraform init

      - name: Terraform Plan
        working-directory: environments/prod
        run: terraform plan -out=tfplan.out

      - name: Upload Plan File
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: environments/prod/tfplan.out

  terraform-apply:
    name: Terraform Apply (Prod)
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: prod  # Triggers manual approval from GitHub Environments (Settings > Environments)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Azure CLI Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download Plan File
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: environments/prod

      - name: Terraform Apply
        working-directory: environments/prod
        run: terraform apply -auto-approve tfplan.out
